markdown_extensions:
  - attr_list
site_name: Enrique Sánchez
nav:
  - Home: index.md
  - My Work:
    - Technical Skills: techskills.md
    - Soft Skills: softskills.md
    - Achievements: achievements.md
  - My Life:
    - Biography: about.md
    - Hobbies: hobbies.md
    - Abilities: abilities.md

theme:
  name: material
  logo: images/logo.png

extra_css: 
  - css/extra.css